// <auto-generated />
using System;
using Medium.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medium.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200812005526_Added_RelationshipingPostWithAuthor")]
    partial class Added_RelationshipingPostWithAuthor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medium.Core.Domain.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmedEmail")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("bit");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f29ee19-ea4b-421d-a796-c2ee446becd2"),
                            ConfirmedEmail = true,
                            CreatedAt = new DateTime(2020, 8, 11, 21, 55, 0, 0, DateTimeKind.Unspecified),
                            Deactivated = false,
                            Deleted = false,
                            Email = "admin.master@email.com",
                            FirstName = "Administrador",
                            LastName = "Master",
                            Password = "Xfxy0vH0lWjwyDiiYyAvL5bh6eYAZ15fFEfODmV4TX8=",
                            Salt = "3vVSUWzIYpk=",
                            UpdatedAt = new DateTime(2020, 8, 11, 21, 55, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin.master"
                        });
                });

            modelBuilder.Entity("Medium.Core.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba9016a9-5a51-4847-ac01-1107dd087c82"),
                            Attachments = "",
                            AuthorId = new Guid("4f29ee19-ea4b-421d-a796-c2ee446becd2"),
                            Content = "Post added in migration",
                            CreatedAt = new DateTime(2020, 8, 11, 21, 55, 0, 0, DateTimeKind.Unspecified),
                            Title = "Post Example",
                            UpdatedAt = new DateTime(2020, 8, 11, 21, 55, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d2c7e1a-b024-495c-b128-0e658f1aa12c"),
                            CreatedAt = new DateTime(2020, 8, 11, 21, 55, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tag 1",
                            UpdatedAt = new DateTime(2020, 8, 11, 21, 55, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Medium.Core.Domain.Post", b =>
                {
                    b.HasOne("Medium.Core.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
